SELECT SAMPLE_PATIENTS.SUBJECT_ID,
	SAMPLE_PATIENTS.HADM_ID,
	CHARTTIME,
	COL_ID,
	COL_VALUE,
	TBL_NAME
FROM
	(SELECT DISTINCT SUBJECT_ID,
			ITEMID,
			HADM_ID
		FROM MIMICIV_HOSP.LABEVENTS
		WHERE ITEMID = 50993
			AND HADM_ID IS NOT NULL
		LIMIT 10000) AS SAMPLE_PATIENTS
JOIN
	(SELECT SUBJECT_ID,
			HADM_ID,
			CHARTTIME,
			ITEMID::TEXT AS COL_ID,
			VALUENUM::TEXT AS COL_VALUE,
			'labevents' AS TBL_NAME
		FROM MIMICIV_HOSP.LABEVENTS AS LABEVENTS_FULL
		UNION ALL SELECT SUBJECT_ID,
			HADM_ID,
			COALESCE(VERIFIEDTIME,

				STARTTIME) AS CHARTTIME,
			MEDICATION AS COL_ID,
			FREQUENCY::TEXT AS COL_VALUE,
			'pharmacy' AS TBL_NAME
		FROM MIMICIV_HOSP.PHARMACY
		UNION ALL SELECT SUBJECT_ID,
			HADM_ID,
			CHARTTIME,
			TEST_ITEMID::TEXT AS COL_ID,
			ORG_NAME AS COL_VALUE,
			'microbiologyevents' AS TBL_NAME
		FROM MIMICIV_HOSP.MICROBIOLOGYEVENTS
		UNION ALL SELECT SUBJECT_ID,
			HADM_ID,
			CHARTDATE AS CHARTTIME,
			ICD_CODE::TEXT AS COL_ID,
			SEQ_NUM::TEXT AS COL_VALUE,
			'procedures_icd' AS TBL_NAME
		FROM MIMICIV_HOSP.PROCEDURES_ICD) AS UNPIVOTED_TABLES ON UNPIVOTED_TABLES.SUBJECT_ID = SAMPLE_PATIENTS.SUBJECT_ID
AND UNPIVOTED_TABLES.HADM_ID = SAMPLE_PATIENTS.HADM_ID;